<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace />
	      <BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>	  
    <OutputPath>$(SolutionDir)\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\User\Documents\תכנות\שנה ב\C#\Enums.cs" Link="Enums.cs" />
  </ItemGroup>
</Project>
